# Generated by Django 4.0.2 on 2022-04-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='likes',
            new_name='upvotes',
        ),
    ]
