# Generated by Django 4.0.2 on 2022-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_title_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upvotes',
            new_name='DownVotes',
        ),
        migrations.AddField(
            model_name='product',
            name='UpVotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
